### ISSUE TITLE
Branching before_install steps for faster setup

### ISSUE THREAD

**Issue by SethMichaelLarson** [armonaut/armonaut#14]
- Gather all `apt-get` requirements from all steps that need to be done within `before_install`
- Add all repositories that need to be added via `add-apt-repository`
- Perform `apt-get update`
- Install all dependencies that are required
- Perform all action paths separately depending on the number of CPUs that the instance has.
- Stitch together all these actions' log files after they occur in the log so the user still receives a nice output.
- Begin the `install` steps.

```yaml
before_install:
  - deps:
       - build-essential
       - liblzma
    repos:
      - python-3.7
    steps:
      - git clone https://github.com/pyenv/pyenv ~/.pyenv
      - ~/.pyenv/install
```
