### ISSUE TITLE
Android Components

### ISSUE THREAD

**Issue by SethMichaelLarson** [armonaut/armonaut#16]
Specific to the Android language as there are many different components for Android.
Instead of specifying a version you specify a list of components:

```yaml
android:
  components:
    # Android SDK
    - android-sdk-22

    # Android NDK
    - android-ndk-r16b

    # BuildTools
    - build-tools-19.1.0

    # Machine images
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17

    # Extra Components
    - extra-google-play-services
```

## Compiling Android NDK for ARMv7 and ARMv8
https://developer.android.com/ndk/guides/standalone_toolchain.html
