### ISSUE TITLE
Shared Compute Units

### ISSUE THREAD

**Issue by SethMichaelLarson** [armonaut/armonaut#7]
Jobs with `compute_shared` are run all together on a single compute instance using a fraction of its resources. They run within Docker containers to stay separate.

```yaml
jobs:
  - python: 2.7
    compute_shared: true
    compute_units: 0.5

  - python: 3.6
    compute_shared: true
    compute_units: 0.5
```
