### ISSUE TITLE
Create the arch options for jobs

### ISSUE THREAD

**Issue by SethMichaelLarson** [armonaut/armonaut#9]
```yaml
jobs:
  - python: 3.6
    arch: armv8
    compute_units: 4

  - python: 3.6
    arch: amd64 # or x86-64
    compute_units: 2

  - python: 3.6
    arch: armv7
    # Compute units defaults to 2 for arch: armv7
```
